# Generated by Django 4.1.3 on 2022-11-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="url",
            field=models.CharField(default="melb_data.csv", max_length=70),
        ),
    ]
