# Generated by Django 4.1.3 on 2022-11-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_project_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="file",
            field=models.FileField(default=None, upload_to="datasets/"),
        ),
    ]
