# Generated by Django 4.1.3 on 2022-11-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_project_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="file",
            field=models.FileField(default="file.csv", upload_to="datasets/"),
        ),
    ]
