# Generated by Django 4.1.3 on 2022-11-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_project_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="file",
            field=models.FileField(upload_to="datasets/"),
        ),
        migrations.AlterField(
            model_name="project", name="url", field=models.CharField(max_length=200),
        ),
    ]
