# Generated by Django 4.1.3 on 2022-11-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_project_file_alter_project_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project", name="name", field=models.CharField(max_length=20),
        ),
    ]
