# Generated by Django 4.1.3 on 2022-11-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_project_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="desc",
            field=models.CharField(default="", max_length=200),
        ),
    ]
