# Generated by Django 4.1.3 on 2022-11-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_project_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="dataname",
            field=models.CharField(default=None, max_length=50),
        ),
    ]
