# Generated by Django 4.1.3 on 2022-11-12 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_project_dataname"),
    ]

    operations = [
        migrations.RemoveField(model_name="project", name="dataname",),
    ]
