# Generated by Django 4.1.3 on 2022-11-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_remove_project_file_project_datafile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="dataFile",
            field=models.FileField(null=True, upload_to="datasets/"),
        ),
        migrations.AlterField(
            model_name="project",
            name="desc",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="url",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
