# Generated by Django 4.1.3 on 2022-11-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_project_datafile_alter_project_desc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="dataFile",
            field=models.FileField(default=None, null=True, upload_to="datasets/"),
        ),
    ]
