# Generated by Django 4.1.3 on 2022-11-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_project_datafile"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="fileName",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
