# Generated by Django 4.1.3 on 2022-12-08 23:03

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_project_filename"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=api.models.upload_to
            ),
        ),
    ]
