# Generated by Django 4.1.3 on 2023-01-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_project_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="imageROC",
            field=models.ImageField(
                blank=True, null=True, upload_to="api\\media\\img\\CurvaROC.png"
            ),
        ),
    ]
