# Generated by Django 4.1.3 on 2023-01-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_project_imageroc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="image",
        ),
        migrations.RemoveField(
            model_name="project",
            name="imageROC",
        ),
        migrations.AddField(
            model_name="project",
            name="images",
            field=models.ImageField(blank=True, null=True, upload_to="img/"),
        ),
    ]
